import sys
import traceback
from PySide6.QtWidgets import QApplication

from utilities import utils
from widgets import watcherWindow

def excepthook(exc_type, exc_value, exc_tb):
    tb = "".join(traceback.format_exception(exc_type, exc_value, exc_tb))
    utils.logError(tb)

if __name__ == "__main__":
    utils.log('====================== PROGRAMM STARTED ======================')
    utils.logError('====================== PROGRAMM STARTED ======================')
    
    sys.excepthook = excepthook
    app = QApplication([])
    widget = watcherWindow.WatcherWindow()
    widget.show()
    result = app.exec()
    sys.exit(result)

    # import cProfile as profile
    # import pstats

    # prof = profile.Profile()
    # prof.enable()

    # prof.disable()
    # stats = pstats.Stats(prof).strip_dirs().sort_stats("cumtime")
    # stats.print_stats(10) # top 10 rows

# to do opened orders to top
# to do parse data from orders
# to do add websocket sync check by time
# to do add root logs handler also for binance logs
# to do request api system (from thread), every request return requestId, check for exceptions, limits

# WARNING:root:WebSocket connection closed: connection was closed uncleanly ("WebSocket opening handshake timeout (peer did not finish the opening handshake in time)"), code: 1006, clean: False, 
# reason: connection was closed uncleanly ("WebSocket opening handshake timeout (peer did not finish the opening handshake in time)")
# 527ERROR:root:Lost connection to Server. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionAborted'>: Connection was aborted locally using 
# ITCPTransport.abortConnection.
# ]. Retrying: 1

# 527WARNING:root:WebSocket connection closed: connection was closed uncleanly ("WebSocket opening handshake timeout (peer did not finish the opening handshake in time)"), code: 1006, clean: False, reason: connection was closed uncleanly ("WebSocket opening handshake timeout (peer did not finish the opening handshake in time)")

# ERROR:root:Lost connection to Server. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionAborted'>: Connection was aborted locally using ITCPTransport.abortConnection.
# ]. Retrying: 1
# 527
# WARNING:root:WebSocket connection closed: connection was closed uncleanly ("WebSocket opening handshake timeout (peer did not finish the opening handshake in time)"), code: 1006, clean: False, 
# reason: connection was closed uncleanly ("WebSocket opening handshake timeout (peer did not finish the opening handshake in time)")
# 527ERROR:root:Lost connection to Server. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionAborted'>: Connection was aborted locally using 
# ITCPTransport.abortConnection.
# ]. Retrying: 1
#WARNING:root:WebSocket connection closed: connection was closed uncleanly ("peer dropped the TCP connection without previous WebSocket closing handshake"), code: 1006, clean: False, reason: connection was closed uncleanly ("peer dropped the TCP connection without previous WebSocket closing handshake")

# maintance
# (403, None, 'https://api.binance.com/api/v3/klines\n{\'symbol\': \'TLMUSDT\', \'interval\': \'1h\', \'startTime\': 1685281485538, \'limit\': 44}
# <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
# <HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
# <TITLE>ERROR: The request could 
# not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>403 ERROR</H1>\n<H2>The request could not be satisfied.</H2>
# <HR noshade size="1px">\nRequest blocked.\nWe can\'t connect to the server for this app or website at this time.
# There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
# <BR clear="all">\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error 
# by reviewing the CloudFront documentation.\n<BR clear="all">\n<HR noshade size="1px">\n<PRE>\nGenerated by cloudfront (CloudFront)
# Request ID: -wFQ0oHeDNCwIa0DQFEBmkDZUxxCIe_DrAF91E52mNGy9ksfctMLWA==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>',
#  <CIMultiDictProxy('Server': 'CloudFront', 'Date': 'Tue, 30 May 2023 09:45:42 GMT', 'Content-Type': 'text/html', 'Content-Length': '919',
#  'Connection': 'keep-alive', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 ce90704f6d2bc1f19459aaf24b07365e.cloudfront.net (CloudFront)',
#  'X-Amz-Cf-Pop': 'SOF50-P1', 'X-Amz-Cf-Id': '-wFQ0oHeDNCwIa0DQFEBmkDZUxxCIe_DrAF91E52mNGy9ksfctMLWA==')>)